import { StyleSheet } from 'react-native';
export const cartStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9F3',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 140,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 12,
  },
  headerEyebrow: {
    color: '#B09B8D',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 3,
  },
  headerTitle: {
    fontSize: 29,
    fontWeight: '900',
    letterSpacing: -0.6,
    color: '#34261F',
  },
  clearCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 9,
    backgroundColor: '#FFF0E8',
    borderRadius: 13,
  },
  clearCartText: {
    fontSize: 11,
    color: '#D94A34',
    fontWeight: '800',
    marginLeft: 5,
  },
  cartHero: {
    minHeight: 150,
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 20,
    borderRadius: 25,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 25,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#9D3B2E',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.17,
    shadowRadius: 12,
  },
  cartHeroCopy: {
    flex: 1,
    zIndex: 1,
  },
  cartHeroEyebrow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  cartHeroEyebrowText: {
    color: '#FFE4A8',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.6,
    marginLeft: 5,
  },
  cartHeroTitle: {
    color: '#FFFFFF',
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 27,
    letterSpacing: -0.5,
  },
  cartHeroCaption: {
    color: '#FFF0E4',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 8,
  },
  cartHeroArt: {
    width: 100,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  cartHeroPlate: {
    width: 82,
    height: 82,
    borderRadius: 31,
    backgroundColor: '#FFF0D9',
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
    elevation: 4,
  },
  cartHeroEmoji: {
    fontSize: 43,
  },
  cartHeroCount: {
    position: 'absolute',
    top: 2,
    right: 0,
    minWidth: 27,
    height: 27,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    backgroundColor: '#34261F',
    borderWidth: 2,
    borderColor: '#FCE8D2',
  },
  cartHeroCountText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
  },
  deliveryProgressTrack: {
    position: 'absolute',
    bottom: 12,
    left: 18,
    right: 18,
    height: 4,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    overflow: 'hidden',
  },
  deliveryProgressFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: '#FFE4A8',
  },
  itemsCountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 13,
  },
  itemsCountTitle: {
    color: '#34261F',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 3,
  },
  itemsCount: {
    fontSize: 11,
    color: '#85776F',
  },
  itemsCountBadge: {
    width: 37,
    height: 37,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 13,
    backgroundColor: '#FFF0E8',
  },
  emptyCartContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 44,
    paddingHorizontal: 40,
  },
  emptyCartArt: {
    width: 132,
    height: 132,
    borderRadius: 45,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-5deg' }],
  },
  emptyCartSparkle: {
    position: 'absolute',
    top: 13,
    right: 11,
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCartTitle: {
    fontSize: 23,
    fontWeight: '900',
    color: '#34261F',
    marginTop: 22,
    marginBottom: 7,
  },
  emptyCartText: {
    fontSize: 14,
    color: '#85776F',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 22,
  },
  browseButton: {
    minWidth: 200,
  },
  cartItemsContainer: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  cartItem: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 21,
    marginBottom: 16,
    padding: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 3,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.09,
    shadowRadius: 12,
  },
  itemImageFrame: {
    width: 116,
    height: 144,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F4E8DA',
  },
  itemImage: {
    width: '100%',
    height: '100%',
  },
  imageShade: {
    ...StyleSheet.absoluteFillObject,
  },
  imageTopRow: {
    position: 'absolute',
    top: 8,
    left: 7,
    right: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  cartItemBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF2D8',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  cartItemBadgeText: {
    color: '#9B431D',
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.4,
    marginLeft: 3,
  },
  imageMeta: {
    position: 'absolute',
    bottom: 9,
    left: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imageRating: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(48, 37, 31, 0.72)',
    borderRadius: 9,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  imageRatingText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    marginLeft: 3,
  },
  imageTimeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  itemContent: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  itemInfo: {
    flex: 1,
    marginRight: 8,
  },
  itemName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#34261F',
    marginBottom: 4,
  },
  itemDescription: {
    fontSize: 12,
    color: '#85776F',
    marginBottom: 4,
    lineHeight: 16,
  },
  itemRestaurant: {
    fontSize: 11,
    color: '#D94A34',
    fontWeight: '500',
  },
  removeButton: {
    padding: 4,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 9,
  },
  quantitySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF4EC',
    borderRadius: 20,
    padding: 4,
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 1,
  },
  quantityText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#34261F',
    marginHorizontal: 12,
    minWidth: 20,
    textAlign: 'center',
  },
  itemPrice: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#D94A34',
  },
  customizeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#FFF0E8',
    borderRadius: 10,
  },
  customizeText: {
    fontSize: 12,
    color: '#D94A34',
    fontWeight: '500',
    marginLeft: 4,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 3,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    marginBottom: 24,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 19,
  },
  summaryIcon: {
    width: 39,
    height: 39,
    borderRadius: 14,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  summaryEyebrow: {
    color: '#B09B8D',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.9,
    marginBottom: 2,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#34261F',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#85776F',
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#34261F',
  },
  freeDeliveryNote: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF0E8',
    padding: 12,
    borderRadius: 13,
    marginTop: 12,
    marginBottom: 20,
  },
  freeDeliveryText: {
    fontSize: 12,
    color: '#D94A34',
    marginLeft: 8,
    flex: 1,
  },
  addressField: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 49,
    paddingHorizontal: 13,
    backgroundColor: '#FFF9F3',
    borderWidth: 1,
    borderColor: '#F1E5DA',
    borderRadius: 14,
    marginTop: 8,
  },
  addressInput: {
    flex: 1,
    fontSize: 13,
    color: '#34261F',
    marginLeft: 9,
  },
  promoCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 20,
  },
  promoInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9F3',
    borderWidth: 1,
    borderColor: '#F1E5DA',
    borderRadius: 15,
    paddingHorizontal: 16,
    height: 50,
    marginRight: 12,
  },
  promoInput: {
    flex: 1,
    fontSize: 16,
    color: '#34261F',
    marginLeft: 12,
  },
  applyButton: {
    paddingHorizontal: 20,
    height: 50,
    backgroundColor: '#F45B43',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    marginTop: 8,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#34261F',
  },
  totalValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#D94A34',
  },
  deliveryEstimate: {
    fontSize: 12,
    color: '#85776F',
    textAlign: 'center',
    marginTop: 16,
    fontStyle: 'italic',
  },
  suggestedContainer: {
    paddingHorizontal: 20,
    marginBottom: 40,
  },
  suggestedEyebrow: {
    color: '#B09B8D',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 4,
  },
  suggestedTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#34261F',
    marginBottom: 13,
  },
  suggestedItem: {
    width: 150,
    marginRight: 12,
    padding: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F5EADF',
  },
  suggestedImage: {
    width: '100%',
    height: 98,
    borderRadius: 12,
    marginBottom: 8,
  },
  suggestedName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#34261F',
    marginTop: 2,
    marginBottom: 3,
  },
  suggestedPrice: {
    fontSize: 14,
    color: '#D94A34',
    fontWeight: 'bold',
  },
  checkoutContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1E5DA',
    elevation: 8,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  checkoutInfo: {
    flex: 1,
  },
  checkoutTotal: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#D94A34',
  },
  checkoutItems: {
    fontSize: 12,
    color: '#85776F',
    marginTop: 2,
  },
  checkoutButton: {
    flex: 1,
    maxWidth: 200,
  }
})