import { StyleSheet } from 'react-native'

export const deliveryChargeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9F3',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    marginTop: 10,
    marginBottom: 24,
  },
  eyebrow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFF0E8',
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 20,
    marginBottom: 14,
  },
  eyebrowText: {
    color: '#D94A34',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginLeft: 6,
  },
  title: {
    color: '#34261F',
    fontSize: 31,
    fontWeight: '800',
    marginBottom: 8,
  },
  intro: {
    color: '#85776F',
    fontSize: 15,
    lineHeight: 22,
  },
  featureCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D94A34',
    borderRadius: 22,
    padding: 18,
    marginBottom: 28,
    elevation: 4,
    shadowColor: '#8E382B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  featureIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    marginRight: 13,
  },
  featureCopy: {
    flex: 1,
  },
  featureTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 4,
  },
  featureText: {
    color: '#FFF3EB',
    fontSize: 12,
    lineHeight: 18,
  },
  sectionTitle: {
    color: '#34261F',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 13,
  },
  feeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 15,
    marginBottom: 11,
    borderWidth: 1,
    borderColor: '#F5EADF',
  },
  feeIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  feeIconFree: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: '#EDF6EC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  feeCopy: {
    flex: 1,
  },
  feeLabel: {
    color: '#34261F',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  feeHint: {
    color: '#94867D',
    fontSize: 12,
  },
  feeAmount: {
    color: '#D94A34',
    fontSize: 17,
    fontWeight: '800',
  },
  freeLabel: {
    color: '#4E8A61',
    fontSize: 14,
    fontWeight: '800',
  },
  noteCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF0E8',
    borderRadius: 17,
    padding: 16,
    marginTop: 12,
  },
  noteText: {
    flex: 1,
    color: '#74594F',
    fontSize: 13,
    lineHeight: 20,
    marginLeft: 10,
  },
})
