import { StyleSheet } from 'react-native';

export const editProfileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F3E9', marginHorizontal: 24 },
  header: { paddingTop: 20, paddingBottom: 8, paddingHorizontal: 4 },
  headerEyebrow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 12 },
  eyebrowText: { color: '#D94A34', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 },
  headerTitle: { fontSize: 36, lineHeight: 39, fontWeight: '900', color: '#27231D', letterSpacing: -1.3 },
  headerSubtitle: { fontSize: 14, lineHeight: 21, color: '#817568', marginTop: 10, maxWidth: 310 },
  profileImageSection: {
    alignItems: 'center', paddingVertical: 23, backgroundColor: '#FFFDFC',
    borderRadius: 28, marginBottom: 25, overflow: 'hidden', position: 'relative',
    borderWidth: 1, borderColor: '#F0E2D5',
  },
  profileAccent: {
    position: 'absolute', top: -18, right: 24, width: 78, height: 78,
    borderRadius: 39, backgroundColor: '#FFF0D9', alignItems: 'center', justifyContent: 'center',
  },
  profileImageContainer: { position: 'relative' },
  profileImage: {
    width: 112, height: 112, borderRadius: 38, borderWidth: 4, borderColor: '#F7C976',
  },
  editImageButton: {
    position: 'absolute', bottom: 1, right: -5, backgroundColor: '#E85D40', width: 38,
    height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center',
    borderWidth: 3, borderColor: '#FFFDFC',
  },
  profileName: { fontSize: 20, fontWeight: '800', color: '#30251F', marginTop: 12 },
  changePhotoPill: {
    flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10,
    backgroundColor: '#FFF0E8', paddingHorizontal: 13, paddingVertical: 7, borderRadius: 20,
  },
  changePhotoText: { fontSize: 12, color: '#D94A34', fontWeight: '700' },
  sectionHeading: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 11, paddingHorizontal: 2 },
  sectionTitle: { fontSize: 19, fontWeight: '800', color: '#30251F' },
  sectionHint: { fontSize: 11, color: '#A18E7E' },
  infoContainer: {
    backgroundColor: '#FFFEFB', borderRadius: 24, paddingHorizontal: 15, paddingVertical: 8,
    borderWidth: 1, borderColor: '#EFE5D7', shadowColor: '#4B3829', shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.06, shadowRadius: 14, elevation: 3,
  },
  fieldContainer: { paddingVertical: 10 },
  fieldHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 7 },
  fieldLabel: { fontSize: 12, fontWeight: '800', color: '#8F7969', marginLeft: 8, letterSpacing: 0.25 },
  fieldContent: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    backgroundColor: '#FAF6EF', borderRadius: 14, paddingHorizontal: 13, paddingVertical: 12,
    borderWidth: 1, borderColor: '#F1E9DD',
  },
  fieldValue: { fontSize: 14, color: '#382C25', flex: 1, marginRight: 10, fontWeight: '600' },
  separator: { height: 1, backgroundColor: '#F2EAE0', marginVertical: 2 },
  buttonContainer: { paddingTop: 20, paddingHorizontal: 4 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(37, 29, 23, 0.72)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { backgroundColor: '#FFFEFB', borderRadius: 26, padding: 22, width: '100%', maxWidth: 420, borderWidth: 1, borderColor: '#EFE5D7' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: '800', color: '#30251F' },
  modalInput: { borderWidth: 1, borderColor: '#E9DFD2', borderRadius: 15, backgroundColor: '#FAF6EF', padding: 15, fontSize: 16, minHeight: 52, color: '#30251F' },
  bioInput: { minHeight: 100, textAlignVertical: 'top' },
  modalButtons: { flexDirection: 'row', gap: 12 },
  modalButton: { flex: 1 },
});
