import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const editProfileStyles = StyleSheet.create({
  container: { flex: 1, paddingHorizontal: 20, marginHorizontal: 20 },
  header: { alignItems: 'center', paddingTop: 20 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: Colors.primary, marginBottom: 8 },
  headerSubtitle: { fontSize: 16, color: '#666', textAlign: 'center' },
  profileImageSection: { alignItems: 'center' },
  profileImageContainer: { position: 'relative' },
  profileImage: { width: 120, height: 120, borderRadius: 60, borderWidth: 3, borderColor: Colors.primary },
  editImageButton: { position: 'absolute', bottom: 0, right: 0, backgroundColor: Colors.primary, width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#fff' },
  changePhotoText: { fontSize: 14, color: Colors.primary, fontWeight: '500' },
  infoContainer: { backgroundColor: '#fff', borderRadius: 12, padding: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  fieldContainer: { paddingVertical: 12 },
  fieldHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  fieldLabel: { fontSize: 14, fontWeight: '600', color: '#333', marginLeft: 8 },
  fieldContent: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  fieldValue: { fontSize: 16, color: '#666', flex: 1, marginRight: 12 },
  separator: { height: 1, backgroundColor: '#f0f0f0', marginVertical: 4 },
  buttonContainer: { paddingHorizontal: 10 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { backgroundColor: '#fff', borderRadius: 16, padding: 24, width: '100%', maxWidth: 400 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: Colors.primary },
  modalInput: { borderWidth: 1, borderColor: '#e0e0e0', borderRadius: 8, padding: 12, fontSize: 16, minHeight: 50 },
  bioInput: { minHeight: 100, textAlignVertical: 'top' },
  modalButtons: { flexDirection: 'row', gap: 12 },
  modalButton: { flex: 1 },
});
