import { StyleSheet } from 'react-native';

export const faqsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F6F0EA' },
  animatedHeader: { position: 'absolute', top: 0, left: 0, right: 0, height: 110, zIndex: 1 },
  header: { borderBottomLeftRadius: 30, borderBottomRightRadius: 30, overflow: 'hidden', marginBottom: 18 },
  headerGradient: {
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 26,
    backgroundColor: '#2E1E1B',
  },
  headerContent: { alignItems: 'flex-start' },
  headerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    marginBottom: 12,
  },
  headerPillText: {
    fontSize: 10,
    color: '#FDE3C8',
    letterSpacing: 1,
    fontWeight: '800',
    marginLeft: 6,
  },
  headerTitle: { fontSize: 30, fontWeight: '900', color: '#fff', marginBottom: 6, letterSpacing: -0.6 },
  headerSubtitle: { fontSize: 14, color: 'rgba(255,255,255,0.8)', lineHeight: 20 },
  searchContainer: { paddingHorizontal: 16, marginBottom: 16 },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#F1E5DA',
    shadowColor: '#2E201C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
  },
  searchIcon: { marginRight: 12 },
  searchInput: { flex: 1, fontSize: 15, color: '#2E241F' },
  tabContainer: { flexDirection: 'row', paddingHorizontal: 16, marginBottom: 16, gap: 10 },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#EFDCCB',
    backgroundColor: '#FFFDFB',
    borderRadius: 16,
    shadowColor: '#2E201C',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  activeTab: { backgroundColor: '#E85D40', borderColor: '#E85D40' },
  tabText: { marginLeft: 8, fontSize: 14, fontWeight: '700', color: '#895D4B' },
  activeTabText: { color: '#fff' },
  categoriesScroll: { marginBottom: 18, marginHorizontal: 16 },
  categoriesContainer: { paddingHorizontal: 16 },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#FFFDFB',
    borderWidth: 1,
    borderColor: '#F1E5DA',
    marginRight: 10,
    minHeight: 38,
  },
  categoryButtonActive: { backgroundColor: '#2E1E1B', borderColor: '#2E1E1B' },
  categoryButtonText: { marginLeft: 6, fontSize: 12, fontWeight: '700', color: '#6D5047' },
  categoryButtonTextActive: { color: '#fff' },
  controlsContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, marginBottom: 14 },
  resultsText: { fontSize: 13, color: '#685652', fontWeight: '700' },
  controlButtons: { flexDirection: 'row' },
  controlButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: '#FDF0EA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F0D8C5',
  },
  controlButtonText: { marginLeft: 4, fontSize: 12, color: '#B75B3D', fontWeight: '700' },
  faqListContainer: { flex: 1 },
  faqList: { paddingHorizontal: 16, paddingBottom: 100 },
  faqItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F1E5DA',
    shadowColor: '#2E201C',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
  },
  faqQuestionContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
  faqQuestionContainerExpanded: { borderBottomWidth: 1, borderBottomColor: '#F5EADF' },
  faqQuestionContent: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  questionNumber: { marginRight: 12 },
  numberGradient: { width: 32, height: 32, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  numberText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  questionTextContainer: { flex: 1 },
  faqQuestion: { fontSize: 15, fontWeight: '800', color: '#2F241F', lineHeight: 22 },
  faqAnswerContainer: { padding: 16 },
  answerLine: { height: 3, width: 44, backgroundColor: '#E85D40', borderRadius: 999, marginBottom: 12 },
  faqAnswer: { fontSize: 14, lineHeight: 22, color: '#685C57', marginBottom: 16 },
  answerFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  categoryTag: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF2EA', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 12 },
  categoryTagText: { fontSize: 10, color: '#B75B3D', fontWeight: '800', marginLeft: 4 },
  helpfulButton: { flexDirection: 'row', alignItems: 'center' },
  helpfulText: { fontSize: 12, color: '#B75B3D', marginLeft: 4, fontWeight: '700' },
  emptyContainer: { alignItems: 'center', padding: 40, backgroundColor: '#FFFFFF', borderRadius: 20, marginTop: 20, borderWidth: 1, borderColor: '#F1E5DA' },
  emptyTitle: { fontSize: 18, fontWeight: '800', color: '#332A27', marginTop: 16 },
  emptyText: { fontSize: 14, color: '#7A685F', marginTop: 8, textAlign: 'center', lineHeight: 20 },
  emptyButton: { backgroundColor: '#E85D40', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12, marginTop: 20 },
  emptyButtonText: { color: '#fff', fontWeight: '700' },
  contactCta: { marginTop: 24, borderRadius: 22, overflow: 'hidden', borderWidth: 1, borderColor: '#F1E5DA' },
  contactCtaGradient: { padding: 22, alignItems: 'center' },
  contactCtaTitle: { fontSize: 18, fontWeight: '800', color: '#2F241F', marginTop: 12 },
  contactCtaText: { fontSize: 14, color: '#665B56', textAlign: 'center', marginTop: 8, marginBottom: 16, lineHeight: 20 },
  contactCtaButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E85D40', paddingHorizontal: 22, paddingVertical: 12, borderRadius: 12 },
  contactCtaButtonText: { color: '#fff', fontWeight: '700', marginRight: 8 },
  contactContainer: { flex: 1, paddingHorizontal: 16 },
  contactCard: { borderRadius: 22, padding: 20, marginBottom: 20, borderWidth: 1, borderColor: '#F1E5DA' },
  contactHeader: { alignItems: 'center', marginBottom: 24 },
  contactTitle: { fontSize: 24, fontWeight: '800', color: '#2F241F', marginTop: 16 },
  contactSubtitle: { fontSize: 14, color: '#685C57', textAlign: 'center', marginTop: 8, lineHeight: 20 },
  contactMethods: { marginBottom: 24 },
  contactMethod: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 18,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F5EADF',
    shadowColor: '#2E201C',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
  },
  methodIconContainer: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  methodContent: { flex: 1 },
  methodTitle: { fontSize: 16, fontWeight: '800', color: '#2E241F', marginBottom: 4 },
  methodDescription: { fontSize: 13, color: '#675C57', marginBottom: 2 },
  methodAvailability: { fontSize: 11, color: '#B75B3D', fontWeight: '700' },
  quickLinks: { marginBottom: 24 },
  quickLinksTitle: { fontSize: 18, fontWeight: '800', color: '#2F241F', marginBottom: 12 },
  quickLinksGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  quickLinkItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#F5EADF',
  },
  quickLinkText: { fontSize: 12, color: '#2F241F', fontWeight: '700' },
  feedbackSection: { alignItems: 'center', padding: 20, backgroundColor: '#FFFDFB', borderRadius: 20, borderWidth: 1, borderColor: '#F5EADF' },
  feedbackTitle: { fontSize: 18, fontWeight: '800', color: '#2F241F', marginBottom: 8 },
  feedbackText: { fontSize: 14, color: '#665B56', textAlign: 'center', marginBottom: 16 },
  feedbackButton: { backgroundColor: '#E85D40', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  feedbackButtonText: { color: '#fff', fontWeight: '700' },
});
