import { StyleSheet } from 'react-native';

export const faqsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8f9fa" },
  animatedHeader: { position: "absolute", top: 0, left: 0, right: 0, height: 100, zIndex: 1 },
  header: { borderBottomLeftRadius: 20, borderBottomRightRadius: 20, overflow: "hidden", marginBottom: 16 },
  headerGradient: { padding: 24 },
  headerContent: { alignItems: "center" },
  headerTitle: { fontSize: 28, fontWeight: "bold", color: "#fff", marginBottom: 4 },
  headerSubtitle: { fontSize: 14, color: "rgba(255, 255, 255, 0.9)" },
  searchContainer: { paddingHorizontal: 16, marginBottom: 16 },
  searchInputContainer: { flexDirection: "row", alignItems: "center", backgroundColor: "#fff", borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, elevation: 2, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  searchIcon: { marginRight: 12 },
  searchInput: { flex: 1, fontSize: 16, color: "#333" },
  tabContainer: { flexDirection: "row", paddingHorizontal: 16, marginBottom: 16 },
  tab: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 12, borderWidth: 1, borderColor: "#6849a7", backgroundColor: "#fff", marginRight: 8, borderRadius: 10 },
  activeTab: { backgroundColor: "#6849a7" },
  tabText: { marginLeft: 8, fontSize: 14, fontWeight: "600", color: "#6849a7" },
  activeTabText: { color: "#fff" },
  categoriesScroll: { marginBottom: 16 },
  categoriesContainer: { paddingHorizontal: 16 },
  categoryButton: { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 6, borderRadius: 20, backgroundColor: "#fff", borderWidth: 1, borderColor: "#e0e0e0", marginRight: 8, height: 32 },
  categoryButtonActive: { backgroundColor: "#6849a7", borderColor: "#6849a7" },
  categoryButtonText: { marginLeft: 6, fontSize: 12, fontWeight: "500", color: "#666" },
  categoryButtonTextActive: { color: "#fff" },
  controlsContainer: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 16, marginBottom: 16 },
  resultsText: { fontSize: 14, color: "#666" },
  controlButtons: { flexDirection: "row" },
  controlButton: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingVertical: 6, backgroundColor: "#f0e6ff", borderRadius: 16 },
  controlButtonText: { marginLeft: 4, fontSize: 12, color: "#6849a7", fontWeight: "500" },
  faqListContainer: { flex: 1 },
  faqList: { paddingHorizontal: 16, paddingBottom: 100 },
  faqItem: { backgroundColor: "#fff", borderRadius: 12, marginBottom: 12, overflow: "hidden", elevation: 2, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  faqQuestionContainer: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16 },
  faqQuestionContainerExpanded: { borderBottomWidth: 1, borderBottomColor: "#f0f0f0" },
  faqQuestionContent: { flex: 1, flexDirection: "row", alignItems: "center" },
  questionNumber: { marginRight: 12 },
  numberGradient: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  numberText: { color: "#fff", fontWeight: "bold", fontSize: 14 },
  questionTextContainer: { flex: 1 },
  faqQuestion: { fontSize: 16, fontWeight: "600", color: "#333", lineHeight: 22 },
  faqAnswerContainer: { padding: 16 },
  answerLine: { height: 3, width: 40, backgroundColor: "#6849a7", borderRadius: 2, marginBottom: 12 },
  faqAnswer: { fontSize: 14, lineHeight: 22, color: "#666", marginBottom: 16 },
  answerFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  categoryTag: { flexDirection: "row", alignItems: "center", backgroundColor: "#f0e6ff", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  categoryTagText: { fontSize: 10, color: "#6849a7", fontWeight: "500", marginLeft: 4 },
  helpfulButton: { flexDirection: "row", alignItems: "center" },
  helpfulText: { fontSize: 12, color: "#6849a7", marginLeft: 4 },
  emptyContainer: { alignItems: "center", padding: 40, backgroundColor: "#fff", borderRadius: 12, marginTop: 20 },
  emptyTitle: { fontSize: 18, fontWeight: "600", color: "#666", marginTop: 16 },
  emptyText: { fontSize: 14, color: "#999", marginTop: 8, textAlign: "center" },
  emptyButton: { backgroundColor: "#6849a7", paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8, marginTop: 20 },
  emptyButtonText: { color: "#fff", fontWeight: "600" },
  contactCta: { marginTop: 24, borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: "#e0e0e0" },
  contactCtaGradient: { padding: 24, alignItems: "center" },
  contactCtaTitle: { fontSize: 18, fontWeight: "bold", color: "#333", marginTop: 12 },
  contactCtaText: { fontSize: 14, color: "#666", textAlign: "center", marginTop: 8, marginBottom: 16, lineHeight: 20 },
  contactCtaButton: { flexDirection: "row", alignItems: "center", backgroundColor: "#6849a7", paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 },
  contactCtaButtonText: { color: "#fff", fontWeight: "600", marginRight: 8 },
  // Contact Tab Styles
  contactContainer: { flex: 1, paddingHorizontal: 16 },
  contactCard: { borderRadius: 16, padding: 20, marginBottom: 20 },
  contactHeader: { alignItems: "center", marginBottom: 24 },
  contactTitle: { fontSize: 24, fontWeight: "bold", color: "#333", marginTop: 16 },
  contactSubtitle: { fontSize: 14, color: "#666", textAlign: "center", marginTop: 8, lineHeight: 20 },
  contactMethods: { marginBottom: 24 },
  contactMethod: { flexDirection: "row", alignItems: "center", backgroundColor: "#fff", padding: 16, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: "#f0f0f0" },
  methodIconContainer: { width: 48, height: 48, borderRadius: 24, alignItems: "center", justifyContent: "center", marginRight: 16 },
  methodContent: { flex: 1 },
  methodTitle: { fontSize: 16, fontWeight: "600", color: "#333", marginBottom: 4 },
  methodDescription: { fontSize: 14, color: "#666", marginBottom: 2 },
  methodAvailability: { fontSize: 12, color: "#6849a7", fontWeight: "500" },
  quickLinks: { marginBottom: 24 },
  quickLinksTitle: { fontSize: 18, fontWeight: "600", color: "#333", marginBottom: 12 },
  quickLinksGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
  quickLinkItem: { width: "48%", flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#fff", padding: 12, borderRadius: 8, marginBottom: 8, borderWidth: 1, borderColor: "#f0f0f0" },
  quickLinkText: { fontSize: 12, color: "#333", fontWeight: "500" },
  feedbackSection: { alignItems: "center", padding: 20, backgroundColor: "#fff", borderRadius: 12, borderWidth: 1, borderColor: "#f0f0f0" },
  feedbackTitle: { fontSize: 18, fontWeight: "600", color: "#333", marginBottom: 8 },
  feedbackText: { fontSize: 14, color: "#666", textAlign: "center", marginBottom: 16 },
  feedbackButton: { backgroundColor: "#6849a7", paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8 },
  feedbackButtonText: { color: "#fff", fontWeight: "600" },
});
