import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const favouritesStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: Colors.primary },
  headerActions: { flexDirection: 'row', gap: 12 },
  headerButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.primary + '15', alignItems: 'center', justifyContent: 'center' },
  headerSubtitle: { fontSize: 14, color: '#666' },
  selectionModeBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: Colors.primary + '10', paddingHorizontal: 20, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: Colors.primary + '20' },
  selectionCount: { fontSize: 14, fontWeight: '500', color: Colors.primary },
  removeSelectedButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.primary, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, gap: 6 },
  removeSelectedText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8f9fa', marginHorizontal: 20, marginBottom: 16, paddingHorizontal: 16, borderRadius: 12, height: 50 },
  searchIcon: { marginRight: 12 },
  searchInput: { flex: 1, fontSize: 16, color: '#333', height: '100%' },
  categoriesContainer: { marginBottom: 16 },
  categoriesContent: { paddingHorizontal: 20 },
  categoryButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: '#f8f9fa', marginRight: 10, height: 32 },
  activeCategoryButton: { backgroundColor: Colors.primary },
  categoryText: { fontSize: 14, fontWeight: '500', color: Colors.primary, marginLeft: 6 },
  activeCategoryText: { color: '#fff' },
  sortContainer: { paddingHorizontal: 20, marginBottom: 20 },
  sortLabel: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8 },
  sortOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sortOption: { paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#f8f9fa', borderRadius: 8 },
  activeSortOption: { backgroundColor: Colors.primary },
  sortOptionText: { fontSize: 12, fontWeight: '500', color: '#666' },
  activeSortOptionText: { color: '#fff' },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
  favoriteItem: { backgroundColor: '#fff', borderRadius: 16, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, flexDirection: 'row', position: 'relative' },
  selectionCheckbox: { position: 'absolute', top: 12, left: 12, zIndex: 1, width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: Colors.primary, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  selectionCheckboxSelected: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  itemImage: { width: 100, height: 120, borderTopLeftRadius: 16, borderBottomLeftRadius: 16 },
  itemContent: { flex: 1, padding: 12 },
  itemHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  itemInfo: { flex: 1, marginRight: 8 },
  itemTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  itemName: { fontSize: 16, fontWeight: 'bold', color: '#333', flex: 1 },
  discountBadge: { backgroundColor: '#FF6B6B', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 2, marginLeft: 8 },
  discountText: { fontSize: 10, color: '#fff', fontWeight: 'bold' },
  restaurantRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  restaurantName: { fontSize: 12, color: '#666', marginLeft: 4, marginRight: 12 },
  deliveryInfo: { flexDirection: 'row', alignItems: 'center' },
  deliveryTime: { fontSize: 11, color: '#666', marginLeft: 4 },
  itemDescription: { fontSize: 12, color: '#666', lineHeight: 16 },
  heartButton: { padding: 4 },
  tagsContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8, gap: 4 },
  tag: { backgroundColor: Colors.primary + '10', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  tagText: { fontSize: 10, color: Colors.primary, fontWeight: '500' },
  itemFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
  priceRatingContainer: { flex: 1 },
  priceContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  itemPrice: { fontSize: 18, fontWeight: 'bold', color: Colors.primary, marginRight: 8 },
  originalPrice: { fontSize: 12, color: '#999', textDecorationLine: 'line-through' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center' },
  ratingText: { fontSize: 12, fontWeight: '600', color: '#333', marginLeft: 4 },
  addButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.primary, alignItems: 'center', justifyContent: 'center' },
  unavailableBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#FF6B6B' + '20', borderRadius: 8 },
  unavailableText: { fontSize: 12, color: '#FF6B6B', fontWeight: '500', marginLeft: 4 },
  suggestionsCard: { backgroundColor: '#fff', borderRadius: 16, padding: 20, marginBottom: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, alignItems: 'center' },
  suggestionsTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  suggestionsText: { fontSize: 14, color: '#666', textAlign: 'center', marginBottom: 20, lineHeight: 20 },
  suggestionsButton: { minWidth: 200 },
  statsCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  statItem: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 20, fontWeight: 'bold', color: Colors.primary, marginTop: 8, marginBottom: 4 },
  statLabel: { fontSize: 12, color: '#666' },
  statDivider: { width: 1, height: 40, backgroundColor: '#f0f0f0' },
  emptyState: { alignItems: 'center', paddingVertical: 60, paddingHorizontal: 40 },
  emptyTitle: { fontSize: 22, fontWeight: 'bold', color: '#333', marginTop: 24, marginBottom: 8 },
  emptyText: { fontSize: 16, color: '#666', textAlign: 'center', marginBottom: 32, lineHeight: 22 },
  browseButton: { minWidth: 180 },
});
