import { StyleSheet } from 'react-native';

export const favouritesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3EFEA',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 16,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#1E1714',
    letterSpacing: 0.2,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: '#F7EFE8',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E7D2C0',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#7C655E',
  },
  selectionModeBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9F1EA',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E9D8C7',
  },
  selectionCount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#8D5B3D',
  },
  removeSelectedButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8D5B3D',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  removeSelectedText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 16,
    paddingHorizontal: 16,
    borderRadius: 18,
    height: 54,
    borderWidth: 1,
    borderColor: '#E9D7C8',
    shadowColor: '#B77D5D',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#1E1714',
    height: '100%',
  },
  categoriesContainer: {
    marginBottom: 18,
  },
  categoriesContent: {
    paddingHorizontal: 20,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#FBF7F3',
    borderWidth: 1,
    borderColor: '#E9D7C8',
    marginRight: 10,
    height: 38,
  },
  activeCategoryButton: {
    backgroundColor: '#8D5B3D',
    borderColor: '#8D5B3D',
  },
  categoryText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#8D5B3D',
    marginLeft: 6,
  },
  activeCategoryText: {
    color: '#fff',
  },
  sortContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sortLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#41332C',
    marginBottom: 8,
  },
  sortOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sortOption: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F8F2EE',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAD7C9',
  },
  activeSortOption: {
    backgroundColor: '#8D5B3D',
    borderColor: '#8D5B3D',
  },
  sortOptionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#725B52',
  },
  activeSortOptionText: {
    color: '#fff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  favoriteItem: {
    backgroundColor: '#FFFDFB',
    borderRadius: 21,
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#2B201C',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    flexDirection: 'row',
    padding: 8,
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E9D8C7',
  },
  selectionCheckbox: {
    position: 'absolute',
    top: 12,
    left: 12,
    zIndex: 1,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#8D5B3D',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  selectionCheckboxSelected: {
    backgroundColor: '#8D5B3D',
    borderColor: '#8D5B3D',
  },
  itemImageFrame: {
    width: 116,
    height: 144,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F4E8DA',
  },
  itemImage: {
    width: '100%',
    height: '100%',
  },
  imageShade: {
    ...StyleSheet.absoluteFillObject,
  },
  imageTopRow: {
    position: 'absolute',
    top: 8,
    left: 7,
    right: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  popularBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF2D8',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  popularBadgeText: {
    color: '#9B431D',
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.4,
    marginLeft: 3,
  },
  vegetarianBadge: {
    width: 25,
    height: 25,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1FAEF',
  },
  imageMeta: {
    position: 'absolute',
    bottom: 9,
    left: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imageRating: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(48, 37, 31, 0.72)',
    borderRadius: 9,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  imageRatingText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    marginLeft: 3,
  },
  imageTimeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  itemContent: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  itemInfo: {
    flex: 1,
    marginRight: 8,
  },
  itemTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  itemName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E1714',
    flex: 1,
  },
  discountBadge: {
    backgroundColor: '#8D5B3D',
    borderRadius: 7,
    paddingHorizontal: 6,
    paddingVertical: 3,
    marginLeft: 8,
  },
  discountText: {
    fontSize: 10,
    color: '#fff',
    fontWeight: '700',
  },
  restaurantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  restaurantName: {
    fontSize: 12,
    color: '#7A6158',
    marginLeft: 4,
    marginRight: 12,
  },
  deliveryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveryTime: {
    fontSize: 11,
    color: '#7A6158',
    marginLeft: 4,
  },
  itemDescription: {
    fontSize: 12,
    color: '#7A6158',
    lineHeight: 16,
  },
  heartButton: {
    padding: 4,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    gap: 4,
  },
  tag: {
    backgroundColor: '#F8EFE7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E8D7C9',
  },
  tagText: {
    fontSize: 10,
    color: '#8D5B3D',
    fontWeight: '700',
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 9,
  },
  priceRatingContainer: {
    flex: 1,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  itemPrice: {
    fontSize: 18,
    fontWeight: '800',
    color: '#8D5B3D',
    marginRight: 8,
  },
  originalPrice: {
    fontSize: 12,
    color: '#999',
    textDecorationLine: 'line-through',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#43352F',
    marginLeft: 4,
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 15,
    backgroundColor: '#8D5B3D',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8D5B3D',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  unavailableBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#FF6B6B' + '20',
    borderRadius: 8,
  },
  unavailableText: {
    fontSize: 12,
    color: '#FF6B6B',
    fontWeight: '600',
    marginLeft: 4,
  },
  suggestionsCard: {
    backgroundColor: '#FFFDFB',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#2B201C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EAD8C9',
  },
  suggestionsTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E1714',
    marginBottom: 8,
  },
  suggestionsText: {
    fontSize: 14,
    color: '#6A534C',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  suggestionsButton: {
    minWidth: 200,
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFDFB',
    borderRadius: 20,
    padding: 20,
    elevation: 2,
    shadowColor: '#2B201C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#E9D8C7',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: '800',
    color: '#8D5B3D',
    marginTop: 8,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#766460',
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#f0f0f0',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1E1714',
    marginTop: 24,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 16,
    color: '#6A534C',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 22,
  },
  browseButton: {
    minWidth: 180,
  },
});
