import { StyleSheet } from "react-native";

export const heroSectionStyles = StyleSheet.create({
  container: {
    minHeight: 274,
    marginHorizontal: 20,
    marginTop: 14,
    borderRadius: 28,
    overflow: "hidden",
    position: "relative",
  },
  orbit: {
    position: "absolute",
    width: 240,
    height: 240,
    borderRadius: 120,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    right: -115,
    top: -104,
  },
  content: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 26,
  },
  textContainer: {
    flex: 1.2,
    zIndex: 1,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(111, 36, 32, 0.25)",
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignSelf: "flex-start",
    marginBottom: 15,
  },
  badgeText: {
    color: "#FFF7EA",
    fontSize: 9,
    letterSpacing: 1,
    fontWeight: "800",
  },
  heading: {
    fontWeight: "900",
    fontSize: 30,
    lineHeight: 33,
    color: "#000",
    letterSpacing: -0.8,
    marginBottom: 9,
  },
  description: {
    color: "rgba(255, 255, 255, 0.88)",
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 17,
    maxWidth: 205,
  },
  button: {
    flexDirection: "row",
    backgroundColor: "#FFF9F3",
    borderRadius: 22,
    paddingHorizontal: 10,
    paddingVertical: 12,
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
  },
  buttonText: {
    color: "#30251F",
    fontSize: 10,
    fontWeight: "800",
  },
  foodArt: {
    flex: 0.8,
    minWidth: 108,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: -4,
  },
  plate: {
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: "#FFF3DF",
    borderWidth: 8,
    borderColor: "rgba(255,255,255,0.32)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#862F27",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 8,
  },
  foodEmoji: {
    fontSize: 72,
  },
  sparkle: {
    position: "absolute",
    top: 7,
    right: 3,
    width: 31,
    height: 31,
    borderRadius: 16,
    backgroundColor: "#FFCF78",
    alignItems: "center",
    justifyContent: "center",
  },
  sparkleText: {
    fontSize: 20,
    color: "#FFFFFF",
  },
  foodTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 6,
    position: "absolute",
    bottom: 4,
    right: -5,
  },
  foodTagText: {
    color: "#544238",
    fontSize: 9,
    fontWeight: "700",
  },
});
