import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const inboxStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: Colors.primary },
  headerActions: { flexDirection: 'row', gap: 12 },
  headerButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: Colors.primary + '15', alignItems: 'center', justifyContent: 'center' },
  unreadCountBadge: { backgroundColor: Colors.primary + '15', marginHorizontal: 20, paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20, alignSelf: 'flex-start', marginBottom: 16 },
  unreadCountText: { fontSize: 12, fontWeight: '600', color: Colors.primary },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8f9fa', marginHorizontal: 20, marginBottom: 20, paddingHorizontal: 16, borderRadius: 12, height: 50 },
  searchIcon: { marginRight: 12 },
  searchInput: { flex: 1, fontSize: 16, color: '#333', height: '100%' },
  notificationsList: { paddingHorizontal: 20, paddingBottom: 100 },
  sectionHeader: { marginBottom: 12, marginTop: 20 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  notificationItem: { backgroundColor: '#fff', borderRadius: 12, marginBottom: 12, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, position: 'relative' },
  unreadNotification: { borderLeftWidth: 4, borderLeftColor: Colors.primary },
  notificationContent: { flexDirection: 'row', padding: 16 },
  notificationIcon: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
  notificationText: { flex: 1 },
  notificationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  notificationTitle: { fontSize: 16, fontWeight: 'bold', color: '#333', flex: 1, marginRight: 12 },
  notificationTime: { fontSize: 12, color: '#999' },
  notificationMessage: { fontSize: 14, color: '#666', lineHeight: 20, marginBottom: 12 },
  orderInfo: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  orderNumber: { fontSize: 13, color: '#666', marginRight: 12 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 12, fontWeight: '600' },
  actionButton: { alignSelf: 'flex-start', paddingHorizontal: 16, paddingVertical: 8, backgroundColor: Colors.primary + '15', borderRadius: 8 },
  actionText: { fontSize: 14, color: Colors.primary, fontWeight: '500' },
  unreadDot: { position: 'absolute', top: 16, right: 16, width: 8, height: 8, borderRadius: 4, backgroundColor: Colors.primary },
  emptyState: { alignItems: 'center', paddingVertical: 60, paddingHorizontal: 40 },
  emptyTitle: { fontSize: 20, fontWeight: 'bold', color: '#666', marginTop: 20, marginBottom: 8 },
  emptyText: { fontSize: 14, color: '#999', textAlign: 'center', lineHeight: 20 },
});
