import { StyleSheet } from 'react-native';

export const inboxStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9F3',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 13,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: '#34261F',
    letterSpacing: -0.6,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 9,
  },
  headerButton: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inboxHero: {
    minHeight: 154,
    marginHorizontal: 16,
    marginBottom: 13,
    borderRadius: 25,
    paddingHorizontal: 19,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#9D3B2E',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.17,
    shadowRadius: 12,
  },
  inboxHeroCopy: {
    flex: 1,
    zIndex: 1,
  },
  inboxHeroEyebrow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  inboxHeroEyebrowText: {
    color: '#FFE4A8',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.7,
    marginLeft: 5,
  },
  inboxHeroTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
    lineHeight: 26,
    letterSpacing: -0.4,
  },
  inboxHeroCaption: {
    color: '#FFF0E4',
    fontSize: 10,
    fontWeight: '600',
    marginTop: 8,
  },
  inboxHeroArt: {
    width: 94,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  inboxHeroPlate: {
    width: 75,
    height: 75,
    borderRadius: 27,
    backgroundColor: '#FFF0D9',
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
    elevation: 4,
  },
  inboxHeroSparkle: {
    position: 'absolute',
    top: 1,
    right: 0,
  },
  inboxHeroCount: {
    position: 'absolute',
    left: 2,
    bottom: 4,
    minWidth: 27,
    height: 27,
    borderRadius: 10,
    paddingHorizontal: 5,
    backgroundColor: '#34261F',
    borderWidth: 2,
    borderColor: '#FCE8D2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inboxHeroCountText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
  },
  unreadCountBadge: {
    backgroundColor: '#FFF0E8',
    marginHorizontal: 20,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 14,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  unreadCountText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#D94A34',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 18,
    marginBottom: 5,
    paddingHorizontal: 14,
    borderRadius: 16,
    height: 49,
    borderWidth: 1,
    borderColor: '#F1E5DA',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 7,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#34261F',
    height: '100%',
  },
  notificationsList: {
    paddingHorizontal: 18,
    paddingBottom: 36,
  },
  sectionHeader: {
    marginBottom: 10,
    marginTop: 18,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#34261F',
  },
  notificationItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginBottom: 11,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 9,
    position: 'relative',
  },
  unreadNotification: {
    borderColor: '#F8D9CB',
    backgroundColor: '#FFFEFC',
  },
  notificationContent: {
    flexDirection: 'row',
    padding: 14,
  },
  notificationIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  notificationText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 2,
  },
  notificationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  notificationTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#34261F',
    flex: 1,
    marginRight: 8,
    lineHeight: 19,
  },
  notificationTime: {
    fontSize: 10,
    color: '#A3978F',
    marginTop: 2,
  },
  notificationMessage: {
    fontSize: 12,
    color: '#85776F',
    lineHeight: 18,
    marginBottom: 11,
  },
  orderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 11,
  },
  orderNumber: {
    fontSize: 11,
    color: '#6E6057',
    fontWeight: '700',
    marginRight: 9,
  },
  statusBadge: {
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 9,
  },
  statusText: {
    fontSize: 9,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  actionButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: '#FFF0E8',
    borderRadius: 10,
  },
  actionText: {
    fontSize: 11,
    color: '#D94A34',
    fontWeight: '800',
  },
  unreadDot: {
    position: 'absolute',
    top: 15,
    right: 12,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#F45B43',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 58,
    paddingHorizontal: 38,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#34261F',
    marginTop: 18,
    marginBottom: 7,
  },
  emptyText: {
    fontSize: 13,
    color: '#92847B',
    textAlign: 'center',
    lineHeight: 20,
  },
});
