import { StyleSheet } from 'react-native';

export const menuStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9F3',
  },
  menuHero: {
    minHeight: 164,
    marginHorizontal: 14,
    marginTop: 7,
    marginBottom: 13,
    borderRadius: 26,
    paddingHorizontal: 20,
    paddingVertical: 17,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#9D3B2E',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.17,
    shadowRadius: 13,
  },
  heroCopy: {
    flex: 1,
    zIndex: 1,
  },
  heroEyebrow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  heroEyebrowText: {
    color: '#FFE8C6',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.9,
    marginLeft: 5,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 29,
    fontWeight: '900',
    lineHeight: 32,
    letterSpacing: -0.7,
  },
  deliveryPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(117, 37, 31, 0.28)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginTop: 10,
  },
  deliveryPillText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 5,
  },
  heroFoodArt: {
    width: 114,
    height: 126,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 5,
  },
  heroPlate: {
    width: 100,
    height: 100,
    borderRadius: 35,
    backgroundColor: '#FFF0D9',
    borderWidth: 5,
    borderColor: 'rgba(255, 255, 255, 0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-9deg' }],
    elevation: 5,
  },
  heroFoodEmoji: {
    fontSize: 54,
  },
  heroSparkleTop: {
    position: 'absolute',
    top: 1,
    right: 0,
  },
  heroSparkleBottom: {
    position: 'absolute',
    bottom: 3,
    left: 0,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 3,
    backgroundColor: '#FFF9F3',
    zIndex: 2,
  },
  backButton: {
    width: 40,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 5,
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 13,
    height: 48,
    borderWidth: 1,
    borderColor: '#F1E5DA',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 7,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    color: '#34261F',
  },
  filterButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 7,
    position: 'relative',
    backgroundColor: '#FFF0E8',
    borderRadius: 15,
  },
  filterBadge: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: '#34261F',
    borderRadius: 8,
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  categoriesContainer: {
    backgroundColor: '#FFF9F3',
    paddingTop: 14,
    paddingBottom: 11,
    zIndex: 2,
  },
  categoryHeading: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  categoryHeadingTitle: {
    color: '#34261F',
    fontSize: 16,
    fontWeight: '800',
  },
  categoryHeadingNote: {
    color: '#B09B8D',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  categoriesScroll: {
    paddingHorizontal: 16,
  },
  categoryButton: {
    minHeight: 39,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#F1E5DA',
  },
  categoryButtonActive: {
    backgroundColor: '#34261F',
    borderColor: '#34261F',
  },
  categoryEmoji: {
    fontSize: 15,
    marginRight: 6,
  },
  categoryButtonText: {
    color: '#786A61',
    fontSize: 12,
    fontWeight: '700',
  },
  categoryButtonTextActive: {
    color: '#FFFFFF',
  },
  activeFiltersContainer: {
    backgroundColor: '#FFF9F3',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1E5DA',
  },
  activeFilterTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF0E8',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
  },
  activeFilterText: {
    color: '#D94A34',
    fontSize: 12,
    marginHorizontal: 6,
  },
  clearAllButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  clearAllText: {
    color: '#D94A34',
    fontSize: 12,
    fontWeight: '600',
  },
  resultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: '#FFF9F3',
  },
  resultsKicker: {
    color: '#B09B8D',
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 3,
  },
  resultsCount: {
    fontSize: 17,
    fontWeight: '800',
    color: '#34261F',
  },
  sortButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F1E5DA',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  sortText: {
    marginLeft: 4,
    color: '#D94A34',
    fontSize: 11,
    fontWeight: '700',
  },
  menuList: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 32,
  },
  menuItem: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 21,
    marginBottom: 14,
    padding: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 3,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 11,
  },
  menuImageFrame: {
    width: 116,
    height: 144,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: '#F4E8DA',
  },
  menuItemImage: {
    width: '100%',
    height: '100%',
  },
  imageShade: {
    ...StyleSheet.absoluteFillObject,
  },
  imageTopRow: {
    position: 'absolute',
    top: 8,
    left: 7,
    right: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  popularBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF2D8',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  popularBadgeText: {
    color: '#9B431D',
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.4,
    marginLeft: 3,
  },
  vegetarianBadge: {
    width: 25,
    height: 25,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1FAEF',
  },
  imageMeta: {
    position: 'absolute',
    bottom: 9,
    left: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imageRating: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(48, 37, 31, 0.72)',
    borderRadius: 9,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  imageRatingText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    marginLeft: 3,
  },
  imageTime: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageTimeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
    marginLeft: 3,
  },
  menuItemContent: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'space-between',
  },
  menuItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItemName: {
    fontSize: 15,
    fontWeight: '800',
    flex: 1,
    color: '#34261F',
  },
  menuItemDescription: {
    fontSize: 11,
    color: '#85776F',
    marginTop: 5,
    lineHeight: 15,
  },
  menuItemMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  categoryTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF0E8',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 9,
  },
  categoryTagText: {
    fontSize: 9,
    color: '#D94A34',
    fontWeight: '800',
  },
  freshLabel: {
    fontSize: 7,
    color: '#B09B8D',
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  menuItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 7,
  },
  menuItemPrice: {
    fontSize: 18,
    fontWeight: '900',
    color: '#34261F',
  },
  addButton: {
    backgroundColor: '#F45B43',
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#D94A34',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 12,
  },
  emptyContainer: {
    alignItems: 'center',
    padding: 36,
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#F5EADF',
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 25,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#34261F',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 13,
    color: '#92847B',
    marginTop: 7,
    textAlign: 'center',
  },
  emptyButton: {
    backgroundColor: '#F45B43',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 20,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(42, 28, 22, 0.48)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF9F3',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    maxHeight: '80%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  modalBody: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  filterSectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#34261F',
    marginBottom: 10,
    marginTop: 10,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1E5DA',
    borderRadius: 10,
  },
  filterOptionActive: {
    backgroundColor: '#FFF0E8',
  },
  filterOptionText: {
    flex: 1,
    marginLeft: 12,
    fontSize: 14,
    color: '#55483F',
  },
  filterOptionTextActive: {
    color: '#D94A34',
    fontWeight: '700',
  },
  sortOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#F45B43',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#F45B43',
  },
  sortOptionText: {
    marginLeft: 12,
    fontSize: 14,
    color: '#55483F',
  },
  modalFooter: {
    flexDirection: 'row',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1E5DA',
    backgroundColor: '#FFFFFF',
  },
  modalButtonSecondary: {
    flex: 1,
    padding: 15,
    alignItems: 'center',
    backgroundColor: '#FFF0E8',
    borderRadius: 13,
    marginRight: 10,
  },
  modalButtonSecondaryText: {
    color: '#D94A34',
    fontWeight: '700',
  },
  modalButtonPrimary: {
    flex: 1.35,
    padding: 15,
    alignItems: 'center',
    backgroundColor: '#F45B43',
    borderRadius: 13,
  },
  modalButtonPrimaryText: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
});
