import { StyleSheet } from 'react-native';

export const menuStyles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: '#f8f9fa',
  },
  animatedHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    zIndex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    zIndex: 2,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  backButton: { padding: 8, marginRight: 8 },
  searchInputContainer: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: '#f5f5f5', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10 },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: '#333' },
  filterButton: { padding: 8, marginLeft: 8, position: 'relative' },
  filterBadge: { position: 'absolute', top: 4, right: 4, backgroundColor: '#FF6B6B', borderRadius: 8, width: 16, height: 16, alignItems: 'center', justifyContent: 'center' },
  filterBadgeText: { color: '#fff', fontSize: 10, fontWeight: 'bold' },
  categoriesContainer: {
    backgroundColor: '#fff',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    zIndex: 2,
    // marginBottom: 100,
  },
  categoriesScroll: { paddingHorizontal: 16 },
  categoryButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: '#f5f5f5', marginRight: 8 },
  categoryButtonActive: { backgroundColor: '#6849a7' },
  categoryButtonText: { color: '#666', fontWeight: '500' },
  categoryButtonTextActive: { color: '#fff' },
  activeFiltersContainer: { backgroundColor: '#fff', paddingVertical: 12, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: '#f0f0f0', paddingBottom: 100 },
  activeFilterTag: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f0e6ff', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16, marginRight: 8 },
  activeFilterText: { color: '#6849a7', fontSize: 12, marginHorizontal: 6 },
  clearAllButton: { paddingHorizontal: 12, paddingVertical: 6, justifyContent: 'center' },
  clearAllText: { color: '#FF6B6B', fontSize: 12, fontWeight: '500' },
  resultsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 16, backgroundColor: '#fff' },
  resultsCount: { fontSize: 14, color: '#666' },
  sortButton: { flexDirection: 'row', alignItems: 'center' },
  sortText: { marginLeft: 4, color: '#6849a7', fontSize: 14, fontWeight: '500' },
  menuList: { padding: 16, paddingBottom: 100 },
  menuItem: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 12, marginBottom: 16, overflow: 'hidden', elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  menuItemImage: { width: 100, height: 120 },
  menuItemContent: { flex: 1, padding: 12 },
  menuItemHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  menuItemName: { fontSize: 16, fontWeight: '600', flex: 1, color: '#333' },
  vegetarianBadge: { marginLeft: 8 },
  menuItemDescription: { fontSize: 12, color: '#666', marginTop: 4, lineHeight: 16 },
  menuItemMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  ratingContainer: { flexDirection: 'row', alignItems: 'center' },
  ratingText: { fontSize: 12, fontWeight: '600', color: '#333', marginLeft: 4 },
  prepTime: { fontSize: 12, color: '#666' },
  categoryTag: { fontSize: 10, color: '#6849a7', backgroundColor: '#f0e6ff', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  menuItemFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
  menuItemPrice: { fontSize: 18, fontWeight: 'bold', color: '#6849a7' },
  addButton: { backgroundColor: '#6849a7', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  addButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  emptyContainer: { alignItems: 'center', padding: 40 },
  emptyText: { fontSize: 18, fontWeight: '600', color: '#666', marginTop: 16 },
  emptySubtext: { fontSize: 14, color: '#999', marginTop: 8, textAlign: 'center' },
  emptyButton: { backgroundColor: '#6849a7', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8, marginTop: 20 },
  emptyButtonText: { color: '#fff', fontWeight: '600' },
  // Modal Styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '80%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  modalBody: { padding: 20 },
  filterSectionTitle: { fontSize: 16, fontWeight: '600', color: '#333', marginBottom: 12, marginTop: 8 },
  filterOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  filterOptionActive: { backgroundColor: '#f0e6ff' },
  filterOptionText: { flex: 1, marginLeft: 12, fontSize: 16, color: '#333' },
  filterOptionTextActive: { color: '#6849a7', fontWeight: '500' },
  sortOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
  radioButton: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#6849a7', alignItems: 'center', justifyContent: 'center' },
  radioButtonInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#6849a7' },
  sortOptionText: { marginLeft: 12, fontSize: 16, color: '#333' },
  modalFooter: { flexDirection: 'row', padding: 20, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  modalButtonSecondary: { flex: 1, padding: 16, alignItems: 'center', backgroundColor: '#f5f5f5', borderRadius: 12, marginRight: 12 },
  modalButtonSecondaryText: { color: '#666', fontWeight: '600' },
  modalButtonPrimary: { flex: 1, padding: 16, alignItems: 'center', backgroundColor: '#6849a7', borderRadius: 12 },
  modalButtonPrimaryText: { color: '#fff', fontWeight: '600' },
});
