import { StyleSheet } from 'react-native';

export const orderHistoryStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F1EB',
  },
  restaurantHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: '#2C2020',
    borderBottomWidth: 1,
    borderBottomColor: '#49322D',
    shadowColor: '#241713',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 5,
  },
  restaurantImageFrame: {
    padding: 3,
    borderRadius: 20,
    backgroundColor: '#F4B08A',
    marginRight: 14,
  },
  restaurantImage: {
    width: 72,
    height: 72,
    borderRadius: 17,
  },
  restaurantInfo: {
    flex: 1,
  },
  restaurantName: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFF8F2',
    marginBottom: 6,
  },
  restaurantDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  restaurantRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  restaurantRatingText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFF8F2',
    marginLeft: 4,
  },
  restaurantCuisine: {
    fontSize: 14,
    color: '#D7BDB0',
  },
  restaurantDelivery: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  restaurantDeliveryText: {
    fontSize: 13,
    color: '#FFC2A5',
    marginLeft: 5,
    fontWeight: '700',
  },
  restaurantBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF3E8',
    marginLeft: 8,
  },
  sectionTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#261916',
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 5,
    letterSpacing: -0.5,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: '#876D62',
    paddingHorizontal: 20,
    paddingBottom: 18,
  },
  filterContainer: {
    marginBottom: 18,
  },
  filterContent: {
    paddingHorizontal: 20,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 42,
    paddingHorizontal: 15,
    paddingVertical: 0,
    borderRadius: 14,
    backgroundColor: '#FFFDFC',
    borderWidth: 1,
    borderColor: '#EADDD2',
    marginRight: 10,
  },
  activeFilterButton: {
    backgroundColor: '#E85D40',
    borderColor: '#E85D40',
  },
  filterText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#765D53',
  },
  activeFilterText: {
    color: '#fff',
  },
  filterCount: {
    marginLeft: 6,
    backgroundColor: '#F8E4D9',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  activeFilterCount: {
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  filterCountText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#7D6359',
  },
  activeFilterCountText: {
    color: '#fff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  orderCard: {
    backgroundColor: '#FFFDFC',
    borderRadius: 22,
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#241713',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#EADDD2',
    borderLeftWidth: 4,
    borderLeftColor: '#E85D40',
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 17,
  },
  orderHeaderLeft: {
    flex: 1,
  },
  orderBasicInfo: {
    flex: 1,
  },
  orderIdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  orderId: {
    fontSize: 14,
    fontWeight: '800',
    color: '#C64B35',
    marginLeft: 6,
  },
  orderDate: {
    fontSize: 13,
    color: '#6E5A52',
    marginBottom: 6,
  },
  deliveryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deliveryTimeText: {
    fontSize: 12,
    color: '#6E5A52',
    marginLeft: 4,
  },
  orderHeaderRight: {
    alignItems: 'flex-end',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: '#FBE9DF',
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    marginLeft: 4,
  },
  expandIcon: {
    marginTop: 4,
  },
  orderSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 17,
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: '#F0E4DA',
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 11,
    color: '#9A8176',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#33231F',
  },
  totalAmount: {
    fontSize: 16,
    fontWeight: '800',
    color: '#C64B35',
  },
  summaryDivider: {
    width: 1,
    height: 30,
    backgroundColor: '#f0f0f0',
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2F231E',
    marginLeft: 4,
  },
  noRatingText: {
    fontSize: 12,
    color: '#9B8479',
    fontStyle: 'italic',
  },
  orderDetails: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#F5EADF',
    backgroundColor: '#FBF6F0',
  },
  detailsSection: {
    marginBottom: 20,
  },
  detailsTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#33231F',
    marginBottom: 12,
  },
  orderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EFE2D8',
  },
  itemInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemName: {
    fontSize: 14,
    color: '#33231F',
  },
  itemQuantity: {
    fontSize: 12,
    color: '#77635A',
    marginLeft: 8,
  },
  itemPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2F231E',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  infoText: {
    fontSize: 13,
    color: '#61514B',
    marginLeft: 8,
    flex: 1,
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#FBE9DF',
    borderRadius: 12,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#C64B35',
    marginLeft: 6,
  },
  favoritesCard: {
    backgroundColor: '#2C2020',
    borderRadius: 22,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#2B201C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#3B2926',
  },
  favoritesTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFF8F2',
    marginBottom: 4,
  },
  favoritesSubtitle: {
    fontSize: 13,
    color: '#D7BDB0',
    marginBottom: 16,
  },
  favoriteItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  favoriteItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  favoriteRank: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#4A302B',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  favoriteRankText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFC2A5',
  },
  favoriteItemName: {
    fontSize: 14,
    color: '#2F231E',
  },
  favoriteItemCount: {
    fontSize: 12,
    color: '#75615C',
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFDFC',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#2B201C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#EADDD2',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '800',
    color: '#C64B35',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#6E5A52',
    textAlign: 'center',
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#EADDD2',
  },
  reorderSection: {
    backgroundColor: '#FFFDFC',
    borderRadius: 22,
    padding: 24,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#2B201C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: '#EADDD2',
  },
  reorderTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#261916',
    marginTop: 16,
    marginBottom: 8,
  },
  reorderText: {
    fontSize: 14,
    color: '#765D53',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  reorderButton: {
    minWidth: 200,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#261916',
    marginTop: 24,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 16,
    color: '#765D53',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 22,
  },
  emptyButton: {
    minWidth: 180,
  },
});
