import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const orderHistoryStyles = StyleSheet.create({
  container: { flex: 1 },
  restaurantHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  restaurantImage: { width: 70, height: 70, borderRadius: 12, marginRight: 16 },
  restaurantInfo: { flex: 1 },
  restaurantName: { fontSize: 22, fontWeight: 'bold', color: '#333', marginBottom: 6 },
  restaurantDetails: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  restaurantRating: { flexDirection: 'row', alignItems: 'center', marginRight: 12 },
  restaurantRatingText: { fontSize: 14, fontWeight: '600', color: '#333', marginLeft: 4 },
  restaurantCuisine: { fontSize: 14, color: '#666' },
  restaurantDelivery: { flexDirection: 'row', alignItems: 'center' },
  restaurantDeliveryText: { fontSize: 13, color: Colors.primary, marginLeft: 4, fontWeight: '500' },
  sectionTitle: { fontSize: 24, fontWeight: 'bold', color: Colors.primary, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 4 },
  sectionSubtitle: { fontSize: 14, color: '#666', paddingHorizontal: 20, paddingBottom: 16 },
  filterContainer: { marginBottom: 2 },
  filterContent: { paddingHorizontal: 20 },
  filterButton: { flexDirection: 'row', alignItems: 'center', height: 32, paddingHorizontal: 16, paddingVertical: 0, borderRadius: 20, backgroundColor: '#f8f9fa', marginRight: 10 },
  activeFilterButton: { backgroundColor: Colors.primary },
  filterText: { fontSize: 14, fontWeight: '500', color: '#666' },
  activeFilterText: { color: '#fff' },
  filterCount: { marginLeft: 6, backgroundColor: 'rgba(0,0,0,0.1)', borderRadius: 10, minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  activeFilterCount: { backgroundColor: 'rgba(255,255,255,0.3)' },
  filterCountText: { fontSize: 10, fontWeight: 'bold', color: '#666' },
  activeFilterCountText: { color: '#fff' },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
  orderCard: { backgroundColor: '#fff', borderRadius: 16, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, overflow: 'hidden' },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', padding: 16 },
  orderHeaderLeft: { flex: 1 },
  orderBasicInfo: { flex: 1 },
  orderIdRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  orderId: { fontSize: 14, fontWeight: '600', color: Colors.primary, marginLeft: 6 },
  orderDate: { fontSize: 13, color: '#666', marginBottom: 6 },
  deliveryInfo: { flexDirection: 'row', alignItems: 'center' },
  deliveryTimeText: { fontSize: 12, color: '#666', marginLeft: 4 },
  orderHeaderRight: { alignItems: 'flex-end' },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, marginBottom: 8 },
  statusText: { fontSize: 11, fontWeight: '600', marginLeft: 4 },
  expandIcon: { marginTop: 4 },
  orderSummary: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingBottom: 16, borderTopWidth: 1, borderTopColor: '#f0f0f0' },
  summaryItem: { flex: 1, alignItems: 'center' },
  summaryLabel: { fontSize: 11, color: '#999', marginBottom: 4 },
  summaryValue: { fontSize: 14, fontWeight: '600', color: '#333' },
  totalAmount: { fontSize: 16, fontWeight: 'bold', color: Colors.primary },
  summaryDivider: { width: 1, height: 30, backgroundColor: '#f0f0f0' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center' },
  ratingText: { fontSize: 12, fontWeight: '600', color: '#333', marginLeft: 4 },
  noRatingText: { fontSize: 12, color: '#999', fontStyle: 'italic' },
  orderDetails: { padding: 16, borderTopWidth: 1, borderTopColor: '#f0f0f0', backgroundColor: '#f8f9fa' },
  detailsSection: { marginBottom: 20 },
  detailsTitle: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 12 },
  orderItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  itemInfo: { flexDirection: 'row', alignItems: 'center' },
  itemName: { fontSize: 14, color: '#333' },
  itemQuantity: { fontSize: 12, color: '#666', marginLeft: 8 },
  itemPrice: { fontSize: 14, fontWeight: '500', color: '#333' },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  infoText: { fontSize: 13, color: '#666', marginLeft: 8, flex: 1 },
  actionButtons: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  actionButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: Colors.primary + '10', borderRadius: 8 },
  actionButtonText: { fontSize: 12, fontWeight: '500', color: Colors.primary, marginLeft: 6 },
  favoritesCard: { backgroundColor: '#fff', borderRadius: 16, padding: 20, marginBottom: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  favoritesTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  favoritesSubtitle: { fontSize: 13, color: '#666', marginBottom: 16 },
  favoriteItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  favoriteItemLeft: { flexDirection: 'row', alignItems: 'center' },
  favoriteRank: { width: 28, height: 28, borderRadius: 14, backgroundColor: Colors.primary + '20', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  favoriteRankText: { fontSize: 12, fontWeight: 'bold', color: Colors.primary },
  favoriteItemName: { fontSize: 14, color: '#333' },
  favoriteItemCount: { fontSize: 12, color: '#666' },
  statsCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 20, marginBottom: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  statItem: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 24, fontWeight: 'bold', color: Colors.primary, marginBottom: 4 },
  statLabel: { fontSize: 12, color: '#666', textAlign: 'center' },
  statDivider: { width: 1, height: 40, backgroundColor: '#f0f0f0' },
  reorderSection: { backgroundColor: '#fff', borderRadius: 16, padding: 24, alignItems: 'center', elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  reorderTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginTop: 16, marginBottom: 8 },
  reorderText: { fontSize: 14, color: '#666', textAlign: 'center', marginBottom: 20, lineHeight: 20 },
  reorderButton: { minWidth: 200 },
  emptyState: { alignItems: 'center', paddingVertical: 60, paddingHorizontal: 40 },
  emptyTitle: { fontSize: 22, fontWeight: 'bold', color: '#333', marginTop: 24, marginBottom: 8 },
  emptyText: { fontSize: 16, color: '#666', textAlign: 'center', marginBottom: 32, lineHeight: 22 },
  emptyButton: { minWidth: 180 },
});
