import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF9F3',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 19,
    paddingBottom: 42,
    borderBottomLeftRadius: 31,
    borderBottomRightRadius: 31,
    overflow: 'hidden',
  },
  headerDecor: {
    position: 'absolute',
    top: 74,
    right: 22,
    width: 48,
    height: 48,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    transform: [{ rotate: '12deg' }],
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerEyebrow: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFE4A8',
    letterSpacing: 1.1,
    marginBottom: 3,
  },
  headerTitle: {
    fontSize: 29,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.6,
  },
  settingsButton: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    position: 'relative',
    padding: 4,
    borderRadius: 31,
    backgroundColor: 'rgba(255, 255, 255, 0.19)',
  },
  avatarImage: {
    width: 70,
    height: 70,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  avatarPlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 25,
    backgroundColor: '#FFF0D9',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-4deg' }],
  },
  editAvatarButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#34261F',
    width: 26,
    height: 26,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  profileInfo: {
    flex: 1,
    marginLeft: 15,
    minWidth: 0,
  },
  memberPill: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#FFF0D9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 6,
  },
  memberPillText: {
    color: '#9B431D',
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.5,
    marginLeft: 4,
  },
  userName: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  userEmail: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 11,
  },
  userSubtext: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 16,
    maxWidth: 220,
  },
  statsContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(117, 37, 31, 0.22)',
    borderRadius: 13,
    paddingVertical: 9,
    paddingHorizontal: 4,
    marginTop: 8,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 17,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.82)',
  },
  statDivider: {
    width: 1,
    marginVertical: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
  },
  content: {
    paddingHorizontal: 18,
    marginTop: -24,
  },
  loginCard: {
    borderRadius: 22,
    marginBottom: 19,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  loginCardGradient: {
    padding: 14,
  },
  loginCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  loginIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  loginTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  loginEyebrow: {
    color: '#B8826C',
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.6,
    marginBottom: 3,
  },
  loginTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#34261F',
    marginBottom: 3,
  },
  loginSubtitle: {
    fontSize: 10,
    color: '#786A61',
    lineHeight: 14,
  },
  loginArrow: {
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: '#F45B43',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 7,
  },
  quickActions: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 21,
    paddingVertical: 15,
    paddingHorizontal: 8,
    marginBottom: 19,
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 9,
  },
  quickActionItem: {
    flex: 1,
    alignItems: 'center',
  },
  quickActionIcon: {
    width: 43,
    height: 43,
    borderRadius: 15,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 7,
  },
  quickActionText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#786A61',
    textAlign: 'center',
  },
  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  sectionEyebrow: {
    fontSize: 8,
    fontWeight: '900',
    color: '#B09B8D',
    letterSpacing: 1,
    marginBottom: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#34261F',
  },
  sectionHeadingIcon: {
    width: 36,
    height: 36,
    borderRadius: 13,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    overflow: 'hidden',
    marginBottom: 19,
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 9,
  },
  menuItem: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#F7EEE6',
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuIconContainer: {
    width: 41,
    height: 41,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  menuTextContainer: {
    flex: 1,
    minWidth: 0,
  },
  menuLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#34261F',
    marginBottom: 3,
  },
  menuDescription: {
    fontSize: 10,
    color: '#92847B',
  },
  menuItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 6,
  },
  badge: {
    backgroundColor: '#FFF0E8',
    borderRadius: 9,
    minWidth: 25,
    alignItems: 'center',
    paddingHorizontal: 7,
    paddingVertical: 4,
    marginRight: 7,
  },
  badgeText: {
    color: '#D94A34',
    fontSize: 9,
    fontWeight: '900',
  },
  supportCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 9,
  },
  supportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  supportIcon: {
    width: 39,
    height: 39,
    borderRadius: 14,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  supportEyebrow: {
    color: '#B09B8D',
    fontSize: 7,
    fontWeight: '900',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  supportTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#34261F',
  },
  supportText: {
    fontSize: 11,
    color: '#85776F',
    marginBottom: 14,
  },
  supportButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  supportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 7,
    backgroundColor: '#FFF9F3',
    borderWidth: 1,
    borderColor: '#F5EADF',
    borderRadius: 12,
    flex: 1,
    marginHorizontal: 3,
  },
  supportButtonText: {
    fontSize: 10,
    color: '#D94A34',
    fontWeight: '800',
    marginLeft: 5,
  },
  appInfo: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  appVersion: {
    fontSize: 11,
    color: '#A3978F',
    marginBottom: 4,
  },
  appCopyright: {
    fontSize: 10,
    color: '#B6A9A0',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 7,
  },
  logoutText: {
    fontSize: 14,
    color: '#D94A34',
    fontWeight: '800',
    marginLeft: 8,
  },
});
