import { StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFF8F1',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  hero: {
    minHeight: 234,
    paddingTop: 17,
    paddingHorizontal: 23,
    paddingBottom: 37,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: 'hidden',
    position: 'relative',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 21,
    zIndex: 1,
  },
  brandIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: '#FFF9F2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  brandName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1.3,
  },
  brandDot: {
    color: 'rgba(255,255,255,0.77)',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  heroContent: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 1,
  },
  heroCopy: {
    flex: 1,
    paddingRight: 4,
  },
  eyebrow: {
    color: '#FFE8C6',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.1,
    marginBottom: 7,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    letterSpacing: -0.7,
    marginBottom: 7,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.84)',
    fontSize: 11,
    lineHeight: 15,
    maxWidth: 202,
  },
  plate: {
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 5,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: '#FFF1DC',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  foodEmoji: {
    fontSize: 43,
  },
  heroCircle: {
    position: 'absolute',
    width: 190,
    height: 190,
    borderRadius: 95,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.17)',
    right: -91,
    top: 105,
  },
  formContainer: {
    width: 'auto',
    backgroundColor: '#FFFFFF',
    borderRadius: 23,
    marginHorizontal: 17,
    marginTop: -20,
    paddingHorizontal: 20,
    paddingTop: 21,
    paddingBottom: 20,
    elevation: 4,
    shadowColor: '#714A39',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    zIndex: 2,
  },
  formHeading: {
    marginBottom: 17,
  },
  formTitle: {
    color: '#30251F',
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  formSubtitle: {
    color: '#9B8B80',
    fontSize: 11,
  },
  passwordRequirements: {
    marginTop: 7,
    padding: 12,
    backgroundColor: '#FFF8F1',
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#F2E9E1',
  },
  requirementsTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#59483E',
    marginBottom: 7,
  },
  requirementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  requirementText: {
    fontSize: 11,
    color: '#9B8B80',
    marginLeft: 7,
  },
  requirementMet: {
    color: '#E65D40',
    fontWeight: '700',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 2,
  },
  divider: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#EDE4DC',
  },
  dividerText: {
    paddingHorizontal: 13,
    fontSize: 11,
    color: '#A69588',
  },
  socialContainer: {
    width: '100%',
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  loginText: {
    fontSize: 12,
    color: '#85766D',
  },
  loginLink: {
    fontSize: 12,
    color: '#E65D40',
    fontWeight: '800',
    marginLeft: 4,
  },
});
