import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const reviewsStyles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 16 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: Colors.primary, marginBottom: 4 },
  headerSubtitle: { fontSize: 14, color: '#666' },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8f9fa', marginHorizontal: 20, marginBottom: 16, paddingHorizontal: 16, borderRadius: 12, height: 50 },
  searchIcon: { marginRight: 12 },
  searchInput: { flex: 1, fontSize: 16, color: '#333', height: '100%' },
  overviewCard: { backgroundColor: '#fff', marginHorizontal: 20, borderRadius: 16, padding: 20, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  overviewHeader: { flexDirection: 'row' },
  averageRatingContainer: { alignItems: 'center', marginRight: 30, minWidth: 100 },
  averageRating: { fontSize: 36, fontWeight: 'bold', color: Colors.primary, marginBottom: 8 },
  totalReviews: { fontSize: 12, color: '#666', marginTop: 4 },
  ratingDistribution: { flex: 1 },
  distributionRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6, gap: 24 },
  distributionLabel: { flexDirection: 'row', alignItems: 'center', width: 60 },
  distributionCount: { fontSize: 12, color: '#666', marginLeft: 6, minWidth: 20 },
  distributionBarContainer: { flex: 1, height: 8, backgroundColor: '#f0f0f0', borderRadius: 4, overflow: 'hidden', marginLeft: 8 },
  distributionBar: { height: '100%', borderRadius: 4 },
  filterContainer: { marginBottom: 16 },
  filterContent: { paddingHorizontal: 20 },
  filterButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: '#f8f9fa', marginRight: 10, height: 32 },
  activeFilterButton: { backgroundColor: Colors.primary },
  filterText: { fontSize: 14, fontWeight: '500', color: Colors.primary, marginHorizontal: 4 },
  activeFilterText: { color: '#fff' },
  filterCount: { backgroundColor: 'rgba(0,0,0,0.1)', borderRadius: 10, minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  activeFilterCount: { backgroundColor: 'rgba(255,255,255,0.3)' },
  filterCountText: { fontSize: 10, fontWeight: 'bold', color: '#666' },
  activeFilterCountText: { color: '#fff' },
  sortContainer: { paddingHorizontal: 20, marginBottom: 20 },
  sortLabel: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8 },
  sortOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sortOption: { paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#f8f9fa', borderRadius: 8 },
  activeSortOption: { backgroundColor: Colors.primary },
  sortOptionText: { fontSize: 12, fontWeight: '500', color: '#666' },
  activeSortOptionText: { color: '#fff' },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
  reviewCard: { backgroundColor: '#fff', borderRadius: 16, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, overflow: 'hidden' },
  reviewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', padding: 16, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  reviewHeaderLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  dishImage: { width: 60, height: 60, borderRadius: 8, marginRight: 12 },
  reviewBasicInfo: { flex: 1 },
  dishName: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 4 },
  restaurantRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 2 },
  restaurantName: { fontSize: 12, color: '#666', marginLeft: 4 },
  orderInfo: { flexDirection: 'row', alignItems: 'center' },
  orderId: { fontSize: 11, color: '#999', marginLeft: 4 },
  ratingBadge: { alignItems: 'center', backgroundColor: Colors.primary + '10', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12 },
  ratingText: { fontSize: 12, fontWeight: 'bold', color: Colors.primary, marginTop: 4 },
  starsContainer: { flexDirection: 'row' },
  reviewContent: { padding: 16 },
  reviewComment: { fontSize: 14, color: '#333', lineHeight: 20, marginBottom: 16 },
  imagesContainer: { marginBottom: 16 },
  reviewImage: { width: 100, height: 100, borderRadius: 8, marginRight: 8 },
  reviewFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  reviewMeta: { flex: 1 },
  reviewDate: { fontSize: 12, color: '#999', marginBottom: 4 },
  helpfulContainer: { flexDirection: 'row', alignItems: 'center' },
  helpfulCount: { fontSize: 12, color: Colors.primary, marginLeft: 4 },
  reviewActions: { flexDirection: 'row', gap: 12 },
  actionButton: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 6, backgroundColor: Colors.primary + '10', borderRadius: 8 },
  deleteButton: { backgroundColor: '#FF6B6B' + '10' },
  actionText: { fontSize: 12, fontWeight: '500', color: Colors.primary, marginLeft: 4 },
  deleteText: { color: '#FF6B6B' },
  statsCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 20, marginBottom: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  statItem: { flex: 1, alignItems: 'center' },
  statNumber: { fontSize: 20, fontWeight: 'bold', color: Colors.primary, marginTop: 8, marginBottom: 4 },
  statLabel: { fontSize: 12, color: '#666' },
  statDivider: { width: 1, height: 40, backgroundColor: '#f0f0f0' },
  tipsCard: { backgroundColor: '#fff', borderRadius: 16, padding: 20, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  tipsTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginTop: 16, marginBottom: 16 },
  tipItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  tipText: { fontSize: 14, color: '#666', lineHeight: 20, marginLeft: 8, flex: 1 },
  emptyState: { alignItems: 'center', paddingVertical: 60, paddingHorizontal: 40 },
  emptyTitle: { fontSize: 22, fontWeight: 'bold', color: '#333', marginTop: 24, marginBottom: 8 },
  emptyText: { fontSize: 16, color: '#666', textAlign: 'center', marginBottom: 32, lineHeight: 22 },
  emptyButton: { minWidth: 180 },
  // Modal Styles
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { backgroundColor: '#fff', borderRadius: 16, padding: 24, width: '100%', maxWidth: 500, maxHeight: '80%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: Colors.primary },
  modalDishInfo: { flexDirection: 'row', alignItems: 'center' },
  modalDishImage: { width: 60, height: 60, borderRadius: 8, marginRight: 12 },
  modalDishDetails: { flex: 1 },
  modalDishName: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  modalRestaurant: { fontSize: 14, color: '#666', marginTop: 2 },
  editRatingContainer: { alignItems: 'center' },
  editRatingLabel: { fontSize: 16, fontWeight: '600', color: '#333', marginBottom: 12 },
  editStarsContainer: { flexDirection: 'row', gap: 8 },
  editRatingText: { fontSize: 18, fontWeight: 'bold', color: Colors.primary, marginTop: 8 },
  editCommentInput: { borderWidth: 1, borderColor: '#e0e0e0', borderRadius: 12, padding: 16, fontSize: 16, minHeight: 120, textAlignVertical: 'top' },
  modalButtons: { flexDirection: 'row', gap: 12 },
  modalButton: { flex: 1 },
});
