import { StyleSheet } from 'react-native';

export const reviewsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F1ED',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 18,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    marginBottom: 12,
  },
  headerBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#FFDCC6',
    letterSpacing: 1,
  },
  headerTitle: {
    fontSize: 30,
    fontWeight: '800',
    color: '#FFF9F3',
    letterSpacing: 0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: '#F9D7BE',
    fontWeight: '600',
  },
  headerAction: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFDFB',
    marginHorizontal: 20,
    marginTop: -18,
    marginBottom: 16,
    paddingHorizontal: 16,
    borderRadius: 18,
    height: 54,
    borderWidth: 1,
    borderColor: '#F2E2D5',
    shadowColor: '#2A1F1C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#1F1A18',
    height: '100%',
  },
  overviewCard: {
    backgroundColor: '#FFFDFB',
    marginHorizontal: 20,
    borderRadius: 24,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F3E5D9',
    shadowColor: '#2A1F1C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
  },
  overviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  averageRatingContainer: {
    alignItems: 'center',
    marginRight: 20,
    minWidth: 100,
  },
  averageRating: {
    fontSize: 36,
    fontWeight: '800',
    color: '#B85C38',
    marginBottom: 4,
  },
  totalReviews: {
    fontSize: 12,
    color: '#75615C',
    marginTop: 4,
    fontWeight: '600',
  },
  ratingDistribution: {
    flex: 1,
  },
  distributionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  distributionLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 52,
  },
  distributionCount: {
    fontSize: 11,
    color: '#524641',
    marginLeft: 4,
    minWidth: 18,
    fontWeight: '700',
  },
  distributionBarContainer: {
    flex: 1,
    height: 8,
    backgroundColor: '#F3E6DE',
    borderRadius: 999,
    overflow: 'hidden',
    marginLeft: 10,
  },
  distributionBar: {
    height: '100%',
    borderRadius: 999,
  },
  filterContainer: {
    marginBottom: 16,
  },
  filterContent: {
    paddingHorizontal: 20,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#FFFDFB',
    borderWidth: 1,
    borderColor: '#F0DFD3',
    marginRight: 10,
    minHeight: 38,
  },
  activeFilterButton: {
    backgroundColor: '#E85D40',
    borderColor: '#E85D40',
  },
  filterText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#5C463F',
    marginHorizontal: 4,
  },
  activeFilterText: {
    color: '#fff',
  },
  filterCount: {
    backgroundColor: '#F4E6DD',
    borderRadius: 999,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  activeFilterCount: {
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  filterCountText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#5C463F',
  },
  activeFilterCountText: {
    color: '#fff',
  },
  sortContainer: {
    paddingHorizontal: 20,
    marginBottom: 18,
  },
  sortLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4B3A35',
    marginBottom: 8,
  },
  sortOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sortOption: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: '#F7EFEA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EADDD2',
  },
  activeSortOption: {
    backgroundColor: '#F2DCC7',
    borderColor: '#E7B78C',
  },
  sortOptionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#5A453F',
  },
  activeSortOptionText: {
    color: '#3A2A25',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  reviewCard: {
    backgroundColor: '#FFFDFB',
    borderRadius: 22,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#F0E2D7',
    shadowColor: '#2A1F1C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    overflow: 'hidden',
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F5E8DD',
    backgroundColor: '#FFF9F5',
  },
  reviewHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  dishImage: {
    width: 64,
    height: 64,
    borderRadius: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#F0E2D7',
  },
  reviewBasicInfo: {
    flex: 1,
  },
  dishName: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1F1A18',
    marginBottom: 4,
  },
  restaurantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 3,
  },
  restaurantName: {
    fontSize: 12,
    color: '#614F49',
    marginLeft: 4,
    fontWeight: '600',
  },
  orderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  orderId: {
    fontSize: 11,
    color: '#8B7369',
    marginLeft: 4,
    fontWeight: '600',
  },
  ratingBadge: {
    alignItems: 'center',
    backgroundColor: '#F9E7D9',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ECC3A1',
    minWidth: 70,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#B05E3D',
    marginTop: 4,
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewContent: {
    padding: 16,
  },
  reviewComment: {
    fontSize: 14,
    color: '#2E2421',
    lineHeight: 22,
    marginBottom: 16,
  },
  imagesContainer: {
    marginBottom: 16,
  },
  reviewImage: {
    width: 110,
    height: 110,
    borderRadius: 16,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#F0E1D5',
  },
  reviewFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reviewMeta: {
    flex: 1,
  },
  reviewDate: {
    fontSize: 12,
    color: '#8E7267',
    marginBottom: 6,
    fontWeight: '600',
  },
  helpfulContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  helpfulCount: {
    fontSize: 12,
    color: '#A55B3E',
    marginLeft: 4,
    fontWeight: '700',
  },
  reviewActions: {
    flexDirection: 'row',
    gap: 10,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 11,
    paddingVertical: 6,
    backgroundColor: '#F9F0EA',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EAD7C9',
  },
  deleteButton: {
    backgroundColor: '#FFF0F0',
    borderColor: '#F7C3C3',
  },
  actionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7A564C',
    marginLeft: 4,
  },
  deleteText: {
    color: '#D95B5B',
  },
  statsCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFDFB',
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#F0E2D7',
    shadowColor: '#2A1F1C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: '800',
    color: '#B85C38',
    marginTop: 8,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: '#5F504A',
    textAlign: 'center',
    fontWeight: '600',
  },
  statDivider: {
    width: 1,
    height: 42,
    backgroundColor: '#F0E5DD',
  },
  tipsCard: {
    backgroundColor: '#FFFDFB',
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F0E2D7',
    shadowColor: '#2A1F1C',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
  },
  tipsTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1F1A18',
    marginTop: 8,
    marginBottom: 16,
  },
  tipItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  tipText: {
    fontSize: 14,
    color: '#574A46',
    lineHeight: 20,
    marginLeft: 8,
    flex: 1,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 56,
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1F1A18',
    marginTop: 20,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 15,
    color: '#65514B',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  emptyButton: {
    minWidth: 180,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(28, 18, 15, 0.54)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#FFFDFB',
    borderRadius: 26,
    padding: 20,
    width: '100%',
    maxWidth: 500,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: '#F0E2D7',
    shadowColor: '#1F1714',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1F1A18',
  },
  modalDishInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9F2ED',
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: '#F0E2D7',
  },
  modalDishImage: {
    width: 60,
    height: 60,
    borderRadius: 14,
    marginRight: 12,
  },
  modalDishDetails: {
    flex: 1,
  },
  modalDishName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#261E1A',
  },
  modalRestaurant: {
    fontSize: 13,
    color: '#685752',
    marginTop: 2,
    fontWeight: '600',
  },
  editRatingContainer: {
    alignItems: 'center',
    backgroundColor: '#F9F3EE',
    borderRadius: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#F0E2D7',
  },
  editRatingLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2E2421',
    marginBottom: 12,
  },
  editStarsContainer: {
    flexDirection: 'row',
    gap: 8,
  },
  editRatingText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#B85C38',
    marginTop: 8,
  },
  editCommentInput: {
    borderWidth: 1,
    borderColor: '#EAD7C9',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    fontSize: 15,
    minHeight: 120,
    textAlignVertical: 'top',
    color: '#1F1A18',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalButton: {
    flex: 1,
  },
});
