import { StyleSheet } from 'react-native';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 18,
    backgroundColor: '#FFF9F3',
  },
  header: {
    marginHorizontal: -18,
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 21,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#9D3B2E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
  },
  headerTopline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 13,
  },
  headerEyebrow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(117, 37, 31, 0.23)',
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  headerEyebrowText: {
    color: '#FFE4A8',
    fontSize: 8,
    fontWeight: '900',
    letterSpacing: 0.8,
    marginLeft: 5,
  },
  headerArt: {
    width: 43,
    height: 43,
    borderRadius: 15,
    backgroundColor: '#FFF0D9',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '8deg' }],
  },
  headerTitle: {
    fontSize: 29,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: -0.6,
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#FFF0E4',
    lineHeight: 18,
    maxWidth: 270,
  },
  headerChips: {
    flexDirection: 'row',
    marginTop: 14,
  },
  headerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 6,
    marginRight: 7,
  },
  headerChipText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
    marginLeft: 5,
  },
  section: {
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#34261F',
    marginBottom: 9,
    marginLeft: 3,
  },
  sectionContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F5EADF',
    elevation: 2,
    shadowColor: '#563A2E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.055,
    shadowRadius: 9,
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 11,
    paddingHorizontal: 12,
    minHeight: 64,
  },
  itemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  itemIcon: {
    width: 39,
    height: 39,
    borderRadius: 14,
    backgroundColor: '#FFF0E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemIconDanger: {
    backgroundColor: '#FFF0ED',
  },
  itemTextContainer: {
    marginLeft: 11,
    flex: 1,
    minWidth: 0,
  },
  itemTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#34261F',
    marginBottom: 3,
  },
  itemDescription: {
    fontSize: 10,
    color: '#92847B',
  },
  itemSeparator: {
    height: 1,
    backgroundColor: '#F5EADF',
    marginLeft: 62,
  },
  badge: {
    backgroundColor: '#FFF0E8',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  badgeText: {
    color: '#D94A34',
    fontSize: 10,
    fontWeight: '900',
  },
  appInfo: {
    alignItems: 'center',
    paddingVertical: 18,
  },
  appInfoText: {
    fontSize: 10,
    color: '#A3978F',
    marginBottom: 4,
  },
});
